// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utlxwljzrugfmqviwvpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0bHh3bGp6cnVnZm1xdml3dnB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTM3ODAsImV4cCI6MjA2OTM2OTc4MH0.dmB93ekmMFjkuuyaYQDEqRGIbIMyWquMBTq2DHCyCNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});